Stage 2 - Dmitry Milya
polis-mail-ru/2021-nosql-lsm pull request #40
Opened 2021-05-17 19:52 UTC by RealThomasMiles

2021-05-18 07:36 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/dmitry_milya/InMemoryDAO.java
> +        synchronized (storage) {
К сожалению, не понимаю идеи synchroinzed блока тут. Чем он помогает?

2021-05-18 07:36 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/dmitry_milya/InMemoryDAO.java
> +            storage.clear();
На практике я пояснял, почему это может быть не самой лучшей идеей.

2021-05-18 07:37 UTC, Artyomcool commented
PR https://github.com/polis-mail-ru/2021-nosql-lsm/pull/40 и https://github.com/polis-mail-ru/2021-nosql-lsm/pull/41 схожи до степени смешения. Прошу пояснить причины во избежании карательных мер.

2021-05-18 08:08 UTC, incubos requested changes

2021-05-18 15:24 UTC, RealThomasMiles commented on src/main/java/ru/mail/polis/lsm/dmitry_milya/InMemoryDAO.java
> +        synchronized (storage) {
Читал вот этот вопрос на стаковерфлоу https://stackoverflow.com/questions/12115727/thread-safety-with-concurrenthashmap и немного невнимательно прочитал ответ, из-за чего думал, что так нужно делать...

2021-05-18 15:25 UTC, RealThomasMiles commented on src/main/java/ru/mail/polis/lsm/dmitry_milya/InMemoryDAO.java
> +            storage.clear();
Перенес это из предыдущего решения и забыл что-то с этим сделать

2021-05-18 15:26 UTC, RealThomasMiles commented on src/main/java/ru/mail/polis/lsm/dmitry_milya/InMemoryDAO.java
> +public class InMemoryDAO implements DAO {
Да, просто в этой ветке остался

2021-05-18 15:35 UTC, RealThomasMiles commented
> PR #39, #40 и #41 схожи до степени смешения. Прошу пояснить причины во избежании карательных мер.

Большая часть кода была показана на лекции. Думал, что можно оттуда взять уже написанный код.

2021-05-18 15:42 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/dmitry_milya/InMemoryDAO.java
> +        synchronized (storage) {
Боюсь, это никак не спасает, т.к. чтение все равно происходит без блокировки (а если бы происходило с блокировкой - было бы совсем грустно).
Если очень хочется освбодить память, что может быть хорошей идеей, то следует, например, перестать удерживать объект storage по ссылке, присвоив ему другое значение.
https://github.com/polis-mail-ru/2021-nosql-lsm/pull/35/files - вот один из классических примеров, но он относительно избыточен, есть и другие альтернативы.

2021-05-18 15:44 UTC, Artyomcool commented
Код, показанный на лекции, разумеется можно использовать. Конечно же поощряется написание полностью своего кода, но в этом проблемы нет.
Однако во всех трёх PR сходится целиком всё остальное, включая ошибочные/неоптимальные техники, которые я вообще вижу в первый раз.

2021-05-18 16:25 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/dmitrymilya/PersistenceDAO.java
> +        }
Пожалуйста, максимально подробно расскажите, как вы пришли к этому коду.

2021-05-18 16:41 UTC, RealThomasMiles commented on src/main/java/ru/mail/polis/lsm/dmitrymilya/PersistenceDAO.java
> +        }
На лекции FileChannel был открыт с опцией StandardOpenOption.CREATE_NEW, которая не работает, если файл уже существует. Здесь FileChannel открывается просто с опцией WRITE, поэтому сначала нужно удостовериться, что файл существует.

2021-05-18 16:48 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/dmitrymilya/PersistenceDAO.java
> +        }
При этом в строке 94 удаляется файл.

2021-05-18 17:00 UTC, RealThomasMiles commented on src/main/java/ru/mail/polis/lsm/dmitrymilya/PersistenceDAO.java
> +        }
Да... 😢

2021-05-18 17:02 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/dmitrymilya/PersistenceDAO.java
> +        }
И при этом, такое же решение, используется во всех трёх PR. Вы всё еще продолжаете утверждать, что это случайность?

2021-05-18 17:24 UTC, RealThomasMiles commented on src/main/java/ru/mail/polis/lsm/dmitrymilya/PersistenceDAO.java
> +        }
Нет, я ничего и не утверждал, и сам, возможно, более склонен к тому, что такая ситуация может быть не случайной, ведь один из вышеперечисленных PR создан позже моего...
В совместных решениях по предварительному сговору академически непорядочного характера не участвовал.

2021-05-18 17:42 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/dmitrymilya/PersistenceDAO.java
> +        }
Тогда как вы объясняете идентичность подхода с PR, созданного до вас?

2021-05-23 17:48 UTC, Artyomcool commented
0 баллов, заимствование кода.

2021-05-23 17:48 UTC, closed without merging