Alyona Zakharova: Stage 2
polis-mail-ru/2021-nosql-lsm pull request #42
Opened 2021-05-18 14:50 UTC by alyonazakharova

2021-05-18 15:49 UTC, Artyomcool requested changes
Пожалуйста, поправьте работу с read для получения полного балла.

2021-05-18 15:49 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/NotJustInMemoryDAO.java
> +                while (fileChannel.read(size) > 0) {
Операция read формально может прочитать меньше 4х байт. Вплоть до нуля в некоторых случаях (не в этом).
На практике этот код будет обычно работать в силу стечения обстоятельств, но документации он прямо противоречит.

2021-05-18 15:49 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/NotJustInMemoryDAO.java
> +                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)) {
Интересный подход!
Несмотря на то, что он обладает некоторыми недостатками, я думаю будет заслуженно получить 1 дополнительный балл за нестандартность.

2021-05-18 15:49 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/NotJustInMemoryDAO.java
> +        channel.read(value);
Этот метод не обязан прочитать буфер целиком.
Судя по всему, реализация это делает, но документация этого не подтверждает. Лучше иметь это ввиду.

2021-05-18 15:52 UTC, Artyomcool reviewed
https://stackoverflow.com/questions/13129766/first-sentence-should-end-with-a-period
Вы верно поняли, речь идёт о точке в конце предложения)

2021-05-23 17:53 UTC, Artyomcool reviewed
Для получения полного балла, пожалуйста, исправьте замечания.

2021-05-23 17:53 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/NotJustInMemoryDAO.java
> +        while (size.hasRemaining()) {
Код подозрительно похож на строчки 109-112.

2021-05-23 17:53 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/NotJustInMemoryDAO.java
> +            channel.read(size);
Здесь можно получить вечный цикл: файл может быть короче, чем буфер. Пожалуйста, прочитайте документацию по методу.

2021-05-24 17:38 UTC, alyonazakharova commented
@Artyomcool кажется, я немного налажала, использовав Вашу имплементацию чтения в третьей домашке и поздно увидев Ваши комментарии...

2021-06-02 12:10 UTC, Artyomcool commented
Тогда оценка будет выставленна по тому, что было на тот момент, у меня получается с учетом дополнительного балла 8 баллов.

2021-06-02 12:12 UTC, closed without merging