Stage 3 - Dmitry Milya
polis-mail-ru/2021-nosql-lsm pull request #59
Opened 2021-05-21 14:38 UTC by RealThomasMiles

Implemented Merge Iterator

2021-05-21 16:11 UTC, RealThomasMiles commented on src/main/java/ru/mail/polis/lsm/DAO.java
> +    static Iterator<Record> mergeTwoIterators(Iterator<Record> left, Iterator<Record> right) {
А http://www.lizard.ws/ говорит, что сложность - 15...
![image](https://user-images.githubusercontent.com/30018684/119167237-4d3adb00-ba68-11eb-8dd4-48254ba3f7a7.png)

2021-05-23 19:48 UTC, Artyomcool requested changes
Решение интересное, но никто не обещал, что итераторы будут, вообще говоря, конечными. Если напишите соответствующий тест, получите дополнительные баллы.

2021-05-24 12:04 UTC, RealThomasMiles commented
> Решение интересное, но никто не обещал, что итераторы будут, вообще говоря, конечными. Если напишите соответствующий тест, получите дополнительные баллы.

А решение отклоняется, или и без написания теста можно получить баллы?
И ещё не совсем понял, что нужно проверить в тесте.

2021-05-24 13:58 UTC, Artyomcool commented
Решение не корректное, потому что вместо итерирования вы заполняете коллекцию всеми элементами, а потом возвращаете ее итератор. Какие-то баллы все равно будут, даже без исправлений, но они будут минимальными, и к следующему занятию в любом случае появятся тесты, которые перестанут проходить с таким решением.

Попробуйте подать на вход вашему методу два бесконечных (или условно бесконечных) итератора и убедитесь, что он уйдет в бесконечный цикл (пока не кончится память).

2021-05-24 19:21 UTC, RealThomasMiles commented on src/main/java/ru/mail/polis/lsm/DAO.java
> +        public E next() {
Не получается никак тут эту когнитивную сложность уменьшить из-за постоянных hasNext() ? next() : null...

2021-06-02 16:21 UTC, Artyomcool approved these changes
10 баллов за задание, +5 баллов за скорость.

2021-06-02 16:21 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/DAO.java
> +        public E next() {
Сегодня на занятии продемонстрирую

2021-06-02 16:21 UTC, closed without merging