Ponomarev Stepan | Stage 4 | Жизнь моя жестянка...
polis-mail-ru/2021-nosql-lsm pull request #88
Opened 2021-06-13 11:22 UTC by step-ponomarev

2021-06-20 15:21 UTC, step-ponomarev commented
Локально тесты проходит

2021-06-21 07:32 UTC, Artyomcool requested changes
Пожалуйста, избавьтесь от неуместного использования var.
Его ввели в язык для избавления от избыточности объявлений вида:
```
MyVeryLongClassName obj = new MyVeryLongClassName();
```
После этого я вернусь к проверке работы.

2021-06-21 07:32 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/DAO.java
> +        private int compare(@Nullable Record r1, @Nullable Record r2) {
Забавное решение)

2021-06-21 07:32 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/ponomarev/PonomarevDAO.java
> +                storeSize.set(0);
у вас тут гонки, в большом количестве:
1. Между getAndAdd flush мог запуститься дважды.
2. Между sstable.flush и store.clear могли быть положены новые записи в store, вы их теряете из-за store.clear.
3. store.clear() ломает существующие итераторы (да, у меня тоже есть эта ошибка).
4. storeSize.set(0) по тем же причинам невалиден: после sstable.flush/store.clear конкурентно могло быть вставлено неограниченное количество записей.

2021-06-21 07:32 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/ponomarev/PonomarevDAO.java
> +        return StreamSupport
Крайне избыточная конструкция, я бы постарался избегать ее использования в реальном коде (исправлять не обязательно, просто примите к сведению).

2021-06-21 07:32 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/ponomarev/SSTable.java
> +            var fromIndex = fromKey == null ? minIndex : findIndex(fromKey);
Index вместо var значительно упрощает чтение, т.к. читающему не приходится глазами искать тип minIndex и findIndex (особенно с тернарным оператором). Так ли важно сэкономить 2 буквы?

2021-06-21 07:32 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/ponomarev/SSTable.java
> +        var index = findIndex(record.getKey());
Я прошу прощения, но это невозможно читать без IDE. Мне приходится на каждой строчке выискивать тип по всему коду и его запоминать в голове.

2021-06-22 16:42 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/lsm/ponomarev/PonomarevDAO.java
> +                storeSize.set(0);
Да, и правда, совсем забыл.
Насчет 3 не уверен, у меня ведь там странная схема на вывод итератора

2021-06-22 16:54 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/lsm/ponomarev/SSTable.java
> +        var index = findIndex(record.getKey());
Вары капитулировали и обещали не возвращаться.

2021-06-22 16:54 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/lsm/ponomarev/SSTable.java
> +            var fromIndex = fromKey == null ? minIndex : findIndex(fromKey);
Я не поспорить спрашиваю, мне просто интересно, ибо со стороны не совсем ясно. А зачем вообще знать тип индекса тут?

2021-07-05 08:49 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/ponomarev/PonomarevDAO.java
> +                storeSize.set(0);
Напрасно не уверены. Вы должны определиться - либо данные каждый раз вычитываются и копируются полностью на каждый запрос и потом по ним строится итератор (чего в вашем случае не происходит, к счастью, т.к. это ломает идею выдачи итератора на корню); либо всё сломается с вызовом store.clear. Ваша неуверенность говорит о том, что вы используете конструкции, которых не понимаете. Не используйте такие конструкции.

2021-07-05 08:54 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/ponomarev/SSTable.java
> +            var fromIndex = fromKey == null ? minIndex : findIndex(fromKey);
Читая код я должен либо верить названиям переменных, либо типу.
На название типа уходит значительно больше времени, чем на название переменных, поэтому шансы, что он корректен, значительно выше.
Типы проверяет компилятор (на соответствие).
Типы накладывают ограничения на множество допустимых операций.
Чем больше контекста находится в каждой конкретной конструкции, тем меньше контекста нужно держать в голове для ее анализа (и это не значит, что нужна избыточность в виде огромных имен и т.п., это значит что семантический контекст лучше иметь явным).

2021-07-05 09:09 UTC, Artyomcool reviewed
Для того, что вы делаете, вообще не нужны никакие SSTable и прочие странности: можно вполне записать всё в один файл, и код будет проще, и даже работать будет быстрее, чем в текущем виде.
Мы этого не делаем по той причине, что это все еще непозволительно медленно.

2021-07-05 09:09 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/ponomarev/SSTable.java
> +        Path path = getPath(getFileName(index.order));
я правильно понял, что для каждой записи производятся файловые операции?
это настолько дорого, что не будет работать.
при этом вы зачем-то перезаписываете старые файлы, это достаточно сильно ломает возможности по конкурентному доступу, иммутабельность файлов - основная идея LSM.

2021-07-05 09:14 UTC, Artyomcool reviewed
К сожалению, данная имплементация противоречит идеям, рассказанным на лекциях, что выливается в несоответствие требованиям по производительности и (кажется) надежности.
5 баллов.

2021-07-05 09:14 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/ponomarev/SSTable.java
> +                recordsToMerge.add(readRecords(path));
Вы целиком вычитываете весь файл, даже если от него требуется 1-2 записи (находящиеся в конце).

2021-07-05 09:14 UTC, Artyomcool commented
5 баллов.

2021-07-05 09:14 UTC, closed without merging

2021-08-02 11:45 UTC, incubos reviewed
Согласен с оценкой: не больше 5 баллов -- есть серьёзные замечания к производительности и корректности.

2021-08-02 11:45 UTC, incubos commented on src/main/java/ru/mail/polis/lsm/DAO.java
> +        private int compare(@Nullable Record r1, @Nullable Record r2) {
Т.е. `null` больше всех, если я правильно понимаю? При этом `compare(null, null) == 1`?

2021-08-02 11:45 UTC, incubos commented on src/main/java/ru/mail/polis/lsm/ponomarev/PonomarevDAO.java
> +        if (data.isEmpty()) {
В каком случае это условие истинно с учётом `data.add()` выше?

2021-08-02 11:45 UTC, incubos commented on src/main/java/ru/mail/polis/lsm/ponomarev/PonomarevDAO.java
> +        data.add(store.values().iterator());
Мы всегда итерируемся **по всем данным** в памяти, верно?