Alyona Zakharova: Stage 5
polis-mail-ru/2021-nosql-lsm pull request #99
Opened 2021-06-21 08:26 UTC by alyonazakharova

2021-07-05 09:57 UTC, Artyomcool requested changes
Я совершенно не понимаю, как это работает, и работает ли вообще. Буду благодарен за пояснения.

2021-07-05 09:57 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/SSTable.java
> +    public static List<SSTable> loadFromDir(Path dir) throws IOException {
не понимаю, как это у вас работает: вы при записи удаляете начальные файлы, не трогая название конечного, а тут выходите из цикла при отсутствии этих самых начальных файлов.

2021-08-01 19:37 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/SSTable.java
> +    public static List<SSTable> loadFromDir(Path dir) throws IOException {
>>наверное, в LmsDAO стоило добавить автоматический вызов compact
Не все так просто: если у вас внезапно стало слишком много файлов, это означает, что у вас аномальная нагрузка. А если вы во время аномальной нагрузки начнете делать compact, ваш сервис станет недоступным.

Не забывайте о том, что выполнение вашего кода может быть прервано в любой момент - и это не повод терять данные пользователя (соответственно при последующем запуске нужно восстановить состояние). Поэтому случайное название файла вряд ли подойдет, но фиксированное название - вполне сработает.

Пожалуйста, исправьте проблемы в самый короткий срок.

2021-08-02 11:49 UTC, incubos commented
Надо бы подмёрджить master и зарезолвить конфликты, чтобы заработали тесты.

2021-08-02 15:25 UTC, alyonazakharova commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/SSTable.java
> +    public static List<SSTable> loadFromDir(Path dir) throws IOException {
> Не все так просто: если у вас внезапно стало слишком много файлов, это означает, что у вас аномальная нагрузка. А если вы во время аномальной нагрузки начнете делать compact, ваш сервис станет недоступным.

Логично. Кажется, на том занятии, когда было дано это ДЗ, вы сказали, что вообще достаточно и ручного вызова compact.

Почитала сейчас про SizeTiered Compaction Strategy. Разве это не похоже отчасти на то, что я предложила выше? Только я не думала о том, что файлы должны быть одинакового размера

2021-08-02 20:49 UTC, alyonazakharova commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/SSTable.java
> +    public static List<SSTable> loadFromDir(Path dir) throws IOException {
у меня не получается осознать, почему burnAndCompact ломается при первом же добавлении записи(((
![20191230182239](https://user-images.githubusercontent.com/25694552/127921909-3468d62e-a6b9-4c39-a51d-8f819c79e553.jpg)

2021-08-03 08:53 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/SSTable.java
> +    public static List<SSTable> loadFromDir(Path dir) throws IOException {
Посмотрите ещё раз запись практики: у вас есть как возможность логирования, так и возможность использовать отладчик и пошагово пройтись по коду.

2021-08-07 11:00 UTC, alyonazakharova commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/SSTable.java
> +    public static List<SSTable> loadFromDir(Path dir) throws IOException {
Понимаю, что уже поздно и неактуально, но меня теперь мучает вопрос: в тесте мы записываем одну и ту же запись и после вызова compact() ожидаемо получаем файл меньшего размера. Но если бы мы в основном добавляли новые записи, а не обновляли и удаляли их, размер файла, получаемого после компакшена, с каждым вызовом бы только рос. Не стало бы это проблемой?

2021-08-07 11:03 UTC, alyonazakharova commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/SSTable.java
> +    public static List<SSTable> loadFromDir(Path dir) throws IOException {
Хотя... Наверное, можно просто заранее знать, что происходит чаще, добавление или обновление, и на основе этого знания с адекватной частотой производить компакшен

2021-08-17 16:59 UTC, Artyomcool approved these changes

2021-08-17 16:59 UTC, Artyomcool commented on src/main/java/ru/mail/polis/lsm/alyonazakharova/LmsDAO.java
> +        for (int i = 0; i < compactedSSTables.size(); i++) {
В целом создавать больше одного файла может иметь смысл, чтобы не превышать размер в 2гб адресации ByteBuffer, за это можно было бы обдумать дополнительные баллы.
Но вы допускаете критическую ошибку, которую и с вами мы тоже обсуждали: если исполнение кода прервется до того как вы переименуете скомпакшенные таблички, или же где-то в процессе, вы потеряете данные.
В самом деле, при поднятии сервера вы ничего не делаете c COMPACTED_FILE_PREFIX? загружая только SSTABLE_FILE_PREFIX.

2021-09-26 18:22 UTC, closed without merging